stages:
  - build
  - docker-build
  - deploy

build:
  stage: build
  image: node
  script:
    - echo "Start building App"
    - cd server
    - npm install
    - node -e "require('dotenv').config(); console.log(process.env.DB_USER);"
    - node app &
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd server
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"


deploy:
  stage: deploy
  image: kroniak/ssh-client
  before_script:
    - echo "deploying app"
  script:
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > key.pem
    - chmod 400 key.pem
    - ssh -o StrictHostKeyChecking=no -i key.pem root@$PROD_SERVER_IP "docker pull registry.gitlab.com/christopheryepezch/back-end-fcc"
    - ssh -o StrictHostKeyChecking=no -i key.pem root@$PROD_SERVER_IP "docker stop serverfundacion || true && docker rm serverfundacion || true"
    - ssh -o StrictHostKeyChecking=no -i key.pem root@$PROD_SERVER_IP "docker run -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e DB_HOST=$DB_HOST -e DB_PORT=$DB_PORT -e DB_DATABASE=$DB_DATABASE -e CIE11_CLIENT_ID=$CIE11_CLIENT_ID -e CIE11_CLIENT_SECRET=$CIE11_CLIENT_SECRET -e JWT_SECRET=$JWT_SECRET -e NEW_RELIC_APP_NAME=$NEW_RELIC_APP_NAME -e NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY -e BASE_URL=$BASE_URL -p 5000:5000 -v archivosfcc:/app/src/uploads -d --name serverfundacion registry.gitlab.com/christopheryepezch/back-end-fcc"
